name: discord-consumer
services:
  discord-bot:
    image: ghcr.io/tank-o/csc-discord-consumer:v0.0.3
    env_file: .env.discord-consumer
    volumes:
      - /data/discord-consumer/items.json:/data/items.json
    restart: unless-stopped